Repository scaleway/scaleway-lib, pull requests merged in 2021-05, with the labels that each got.

#148 fix(use-dataloader): avoid exception when options are not defined
  packages/use-dataloader/src/__tests__/useDataLoader.test.js
  packages/use-dataloader/src/useDataLoader.js
Labels: bug

#150 fix: let DataLoaderProvider handle data return from useDataLoader
  packages/use-dataloader/README.md
  packages/use-dataloader/src/__tests__/useDataLoader.test.js
  packages/use-dataloader/src/reducer.js
  packages/use-dataloader/src/useDataLoader.js
Labels: bug, enhancement

#183 feat(i18n): add loaded namespaces and isLoaded into useTranslation
  packages/use-i18n/README.md
  packages/use-i18n/package.json
  packages/use-i18n/src/__tests__/index.js
  packages/use-i18n/src/index.js
  yarn.lock
Labels: enhancement, performance

#196 feat: use dataloader handle enabled changes
  packages/use-dataloader/src/useDataLoader.js
Labels: enhancement, performance

#213 fix: enabled effect and drop unecessary refs
  packages/use-dataloader/src/__tests__/useDataLoader.test.js
  packages/use-dataloader/src/useDataLoader.js
Labels: enhancement
