Repository scaleway/scaleway-lib, pull requests merged in 2022-11, with the labels that each got.

#1079 fix: cron regex
  packages/regex/src/__tests__/index.ts
  packages/regex/src/index.ts
Labels: bug

#1080 feat(eslint): disabled usage of export *
  packages/eslint-config-react/shared.js
  packages/use-i18n/src/index.ts
  packages/use-segment/src/index.ts
  packages/use-segment/src/useSegment.tsx
Labels: documentation, enhancement

#1082 refactor: implement curly rule on gtm
  packages/use-gtm/src/useGTM.tsx
Labels: eslint
